Lethe Open-Source Library: ParticleParticleContactForce< dim, contact_model, rolling_friction_model > Class Template Reference
ParticleParticleContactForce< dim, contact_model, rolling_friction_model > Class Template Reference
#include <particle_particle_contact_force.h>
Public Member Functions
ParticleParticleContactForce (const DEMSolverParameters< dim > &dem_parameters)
virtual ~ParticleParticleContactForce ()
virtual void calculate_particle_particle_contact_force (typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &ghost_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_local_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &local_ghost_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs &ghost_local_periodic_adjacent_particles, const double dt, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force) override
Public Member Functions inherited from ParticleParticleContactForceBase< dim >
void set_periodic_offset (const Tensor< 1, dim > &periodic_offset)
Protected Member Functions
void update_contact_information (particle_particle_contact_info< dim > &contact_info, Tensor< 1, 3 > &tangential_relative_velocity, double &normal_relative_velocity_value, Tensor< 1, 3 > &normal_unit_vector, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const Point< 3 > &particle_one_location, const Point< 3 > &particle_two_location, const double dt)
Point< 3 > get_location (const Particles::ParticleIterator< dim > &particle) &
Point< 3 > get_periodic_location (const Particles::ParticleIterator< dim > &particle) &
void calculate_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
double get_force_calculation_threshold_distance ()
Private Member Functions
void apply_force_and_torque_on_local_particles (const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &tangential_force, const Tensor< 1, 3 > &particle_one_tangential_torque, const Tensor< 1, 3 > &particle_two_tangential_torque, const Tensor< 1, 3 > &rolling_resistance_torque, Tensor< 1, 3 > &particle_one_torque, Tensor< 1, 3 > &particle_two_torque, Tensor< 1, 3 > &particle_one_force, Tensor< 1, 3 > &particle_two_force)
void apply_force_and_torque_on_single_local_particle (const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &tangential_force, const Tensor< 1, 3 > &particle_one_tangential_torque, const Tensor< 1, 3 > &rolling_resistance_torque, Tensor< 1, 3 > &particle_one_torque, Tensor< 1, 3 > &particle_one_force)
std::tuple< double, double > find_effective_radius_and_mass (const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties)
Tensor< 1, 3 > calculate_rolling_resistance_torque (const double effective_radius, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, const double rolling_friction_coeff, const Tensor< 1, 3 > &normal_force, const Tensor< 1, 3 > &normal_unit_vector)
void calculate_linear_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_mindlin_limit_overlap_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_mindlin_limit_force_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_hertz_JKR_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
void calculate_DMT_contact (particle_particle_contact_info< dim > &contact_info, const Tensor< 1, 3 > &tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > &normal_unit_vector, const double normal_overlap, const ArrayView< const double > &particle_one_properties, const ArrayView< const double > &particle_two_properties, Tensor< 1, 3 > &normal_force, Tensor< 1, 3 > &tangential_force, Tensor< 1, 3 > &particle_one_tangential_torque, Tensor< 1, 3 > &particle_two_tangential_torque, Tensor< 1, 3 > &rolling_resistance_torque)
unsigned int vec_particle_type_index (const unsigned int i, const unsigned int j)
void set_effective_properties (const DEMSolverParameters< dim > &dem_parameters)
template<ContactType contact_type>
void execute_contact_calculation (typename DEM::dem_data_structures< dim >::particle_contact_info &adjacent_particles_list, std::vector< Tensor< 1, 3 > > &torque, std::vector< Tensor< 1, 3 > > &force, const double dt)
Private Attributes
unsigned int n_particle_types
std::vector< double > effective_youngs_modulus
std::vector< double > effective_shear_modulus
std::vector< double > effective_coefficient_of_restitution
std::vector< double > effective_coefficient_of_friction
std::vector< double > effective_coefficient_of_rolling_friction
std::vector< double > effective_surface_energy
std::vector< double > effective_hamaker_constant
std::vector< double > model_parameter_beta
const double dmt_cut_off_threshold
Additional Inherited Members
Protected Attributes inherited from ParticleParticleContactForceBase< dim >
Tensor< 1, dim > periodic_offset
Detailed Description
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model>
class ParticleParticleContactForce< dim, contact_model, rolling_friction_model >
Execute calculation of particle-particle contact forces including linear, non-linear contact models, and non-linear with cohesive forces.
Instead of using a inheritance hierarchy to distinguish between the contact model, the class is templated with the type of force model and rolling friction model. Consequently, the code for each combination of force model is generated at compile time.
Template Parameters
dim The dimension of the problem.
force_model The particle-particle contact force model.
rolling_friction_model The rolling resistance model.
Definition at line 102 of file particle_particle_contact_force.h.
Constructor & Destructor Documentation
ParticleParticleContactForce()
template<int dim, ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::ParticleParticleContactForce (const DEMSolverParameters< dim > & dem_parameters)
Definition at line 14 of file particle_particle_contact_force.cc.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::set_effective_properties().
~ParticleParticleContactForce()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> virtual ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::~ParticleParticleContactForce () inline virtual
Definition at line 108 of file particle_particle_contact_force.h.
Member Function Documentation
apply_force_and_torque_on_local_particles()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::apply_force_and_torque_on_local_particles (const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & tangential_force, const Tensor< 1, 3 > & particle_one_tangential_torque, const Tensor< 1, 3 > & particle_two_tangential_torque, const Tensor< 1, 3 > & rolling_resistance_torque, Tensor< 1, 3 > & particle_one_torque, Tensor< 1, 3 > & particle_two_torque, Tensor< 1, 3 > & particle_one_force, Tensor< 1, 3 > & particle_two_force) inline private
Apply the calculated force and torque on the local-local particle pair in contact.
Parameters
[in] normal_force Contact normal force.
[in] tangential_force Contact tangential force.
[in] particle_one_tangential_torque Contact tangential torque on particle one.
[in] particle_two_tangential_torque Contact tangential torque on particle two.
[in] rolling_resistance_torque Contact rolling resistance torque.
[in,out] particle_one_torque
[in,out] particle_two_torque
[in,out] particle_one_force Force acting on particle one
[in,out] particle_two_force Force acting on particle two
Definition at line 461 of file particle_particle_contact_force.h.
apply_force_and_torque_on_single_local_particle()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::apply_force_and_torque_on_single_local_particle (const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & tangential_force, const Tensor< 1, 3 > & particle_one_tangential_torque, const Tensor< 1, 3 > & rolling_resistance_torque, Tensor< 1, 3 > & particle_one_torque, Tensor< 1, 3 > & particle_one_force) inline private
Apply the calculated force and torque on the local-ghost particle pair in contact. The contact force is only applied on the local particles.
Parameters
[in] normal_force Contact normal force.
[in] tangential_force Contact tangential force.
[in] particle_one_tangential_torque Contact tangential torque.
[in] rolling_resistance_torque Contact rolling resistance torque.
[in,out] particle_one_torque Torque acting on particle one (local).
[in,out] particle_one_force Force acting on particle one (local).
Definition at line 496 of file particle_particle_contact_force.h.
calculate_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline protected
Calculate the particle-particle contact force and torque according to the contact model.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 293 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_DMT_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_JKR_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_force_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact(), and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_linear_contact().
calculate_DMT_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_DMT_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Carries out the calculation of the particle-particle DMT contact force and torques based on the updated values in contact_info.
Parameters
contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact
tangential_relative_velocity Tangential relative velocity
normal_relative_velocity_value Normal relative contact velocity
normal_unit_vector Contact normal unit vector
normal_overlap Contact normal overlap
particle_one_properties Properties of particle one in contact
particle_two_properties Properties of particle two in contact
normal_force Contact normal force
tangential_force Contact tangential force
particle_one_tangential_torque Contact tangential torque on particle one
particle_two_tangential_torque Contact tangential torque on particle two
rolling_resistance_torque Contact rolling resistance torque
Definition at line 1302 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_hamaker_constant, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & , const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz contact model, same as the Hertz-Mindlin with limit of the tangential force without the tangential damping force.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 1039 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_JKR_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_JKR_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Carries out the calculation of the particle-particle non-linear contact force and torques based on the updated values in contact_info.
Parameters
contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact
tangential_relative_velocity Tangential relative velocity
normal_relative_velocity_value Normal relative contact velocity
normal_unit_vector Contact normal unit vector
normal_overlap Contact normal overlap
particle_one_properties Properties of particle one in contact
particle_two_properties Properties of particle two in contact
normal_force Contact normal force
tangential_force Contact tangential force
particle_one_tangential_torque Contact tangential torque on particle one
particle_two_tangential_torque Contact tangential torque on particle two
rolling_resistance_torque Contact rolling resistance torque
Definition at line 1156 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_mindlin_limit_force_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_force_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz-Mindlin contact model. If gross sliding occurs, the tangential overlap and tangential force are limited to Coulomb's criterion.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 907 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_hertz_mindlin_limit_overlap_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_hertz_mindlin_limit_overlap_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle non-linear contact force and torque based on the updated values in contact_info. It uses the Hertz-Mindlin contact model. If gross sliding occurs, the tangential overlap is recalculated from the limited tangential to the Coulomb's criterion.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 760 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_linear_contact()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_linear_contact (particle_particle_contact_info< dim > & contact_info, const Tensor< 1, 3 > & tangential_relative_velocity, const double normal_relative_velocity_value, const Tensor< 1, 3 > & normal_unit_vector, const double normal_overlap, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, Tensor< 1, 3 > & normal_force, Tensor< 1, 3 > & tangential_force, Tensor< 1, 3 > & particle_one_tangential_torque, Tensor< 1, 3 > & particle_two_tangential_torque, Tensor< 1, 3 > & rolling_resistance_torque) inline private
Calculate the particle-particle linear contact force and torque based on the updated values in contact_info.
Parameters
[in,out] contact_info A container that contains the required information for calculation of the contact force for a particle pair in contact.
[in] tangential_relative_velocity Tangential relative velocity.
[in] normal_relative_velocity_value Normal relative contact velocity.
[in] normal_unit_vector Contact normal unit vector.
[in] normal_overlap Contact normal overlap.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[out] tangential_force Contact tangential force.
[out] particle_one_tangential_torque Contact tangential torque on particle one.
[out] particle_two_tangential_torque Contact tangential torque on particle two.
[out] rolling_resistance_torque Contact rolling resistance torque.
Definition at line 615 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, particle_particle_contact_info< dim >::tangential_overlap, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index().
calculate_particle_particle_contact_force()
template<int dim, ParticleParticleContactForceModel contact_model, RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_particle_particle_contact_force (typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & local_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & ghost_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & local_local_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & local_ghost_periodic_adjacent_particles, typename DEM::dem_data_structures< dim >::adjacent_particle_pairs & ghost_local_periodic_adjacent_particles, const double dt, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force) override virtual
Calculate the contact forces using the contact pair information obtained in the fine search and physical properties of particles.
Parameters
local_adjacent_particles Container of the contact pair candidates information for calculation of the local particle-particle contact forces.
ghost_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost particle-particle contact forces.
local_local_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the local periodic particle-particle contact forces.
local_ghost_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the local-ghost periodic particle-particle contact forces.
ghost_local_periodic_adjacent_particles Container of the contact pair candidates information for calculation of the ghost-local periodic particle-particle contact forces.
dt DEM time step.
torque Torque acting on particles.
force Force acting on particles.
Implements ParticleParticleContactForceBase< dim >.
Definition at line 25 of file particle_particle_contact_force.cc.
References ghost_local_periodic_particle_particle, ghost_periodic_particle_particle, and local_periodic_particle_particle.
calculate_rolling_resistance_torque()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Tensor< 1, 3 > ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_rolling_resistance_torque (const double effective_radius, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, const double rolling_friction_coeff, const Tensor< 1, 3 > & normal_force, const Tensor< 1, 3 > & normal_unit_vector) inline private
Calculate the rolling resistance torque acting on the particles according to the rolling resistance model.
Parameters
[in] effective_radius Effective radius of the particle pair.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[out] normal_force Contact normal force.
[in] normal_unit_vector Contact normal unit vector.
[out] tangential_force Contact tangential force.
Definition at line 550 of file particle_particle_contact_force.h.
References constant_rolling_resistance_torque(), no_rolling_resistance_torque(), and viscous_rolling_resistance_torque().
execute_contact_calculation()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> template<ContactType contact_type> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::execute_contact_calculation (typename DEM::dem_data_structures< dim >::particle_contact_info & adjacent_particles_list, std::vector< Tensor< 1, 3 > > & torque, std::vector< Tensor< 1, 3 > > & force, const double dt) inline private
Execute the contact calculation step for the particle-particle contact according to the contact type.
Parameters
adjacent_particles_list Container of the adjacent particles of a particles
torque Torque acting on particles.
force Force acting on particles.
dt DEM time step.
Definition at line 1509 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::apply_force_and_torque_on_local_particles(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::apply_force_and_torque_on_single_local_particle(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::calculate_contact(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_force_calculation_threshold_distance(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_location(), ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_periodic_location(), ghost_local_periodic_particle_particle, ghost_particle_particle, ghost_periodic_particle_particle, local_particle_particle, local_periodic_particle_particle, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::update_contact_information().
find_effective_radius_and_mass()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::tuple< double, double > ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::find_effective_radius_and_mass (const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties) inline private
Calculate the effective mass and the effective radius of particle pair.
Parameters
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
Definition at line 518 of file particle_particle_contact_force.h.
References DEM::dp, and DEM::mass.
get_force_calculation_threshold_distance()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> double ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_force_calculation_threshold_distance () inline protected
Calculate the minimum overlap at which particle-particle forces are computed.
Returns
minimum overlap for the force calculation.
Definition at line 417 of file particle_particle_contact_force.h.
References Parameters::Lagrangian::DMT, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::dmt_cut_off_threshold, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_hamaker_constant, and ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_surface_energy.
get_location()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point< 3 > ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_location (const Particles::ParticleIterator< dim > & particle) & inline protected
Get the location of the particle.
Parameters
particle The particle to get the location from.
Definition at line 247 of file particle_particle_contact_force.h.
References point_nd_to_3d().
get_periodic_location()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> Point< 3 > ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::get_periodic_location (const Particles::ParticleIterator< dim > & particle) & inline protected
Get the shifted location of the particle on the periodic boundary.
Parameters
particle The particle to get the location from.
Definition at line 262 of file particle_particle_contact_force.h.
References ParticleParticleContactForceBase< dim >::periodic_offset, and point_nd_to_3d().
set_effective_properties()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::set_effective_properties (const DEMSolverParameters< dim > & dem_parameters) inline private
Set every containers needed to carry the particle-particle force calculation.
Parameters
dem_parameters DEM parameters declared in the .prm file.
Definition at line 1399 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_restitution, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_hamaker_constant, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_surface_energy, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus, harmonic_mean(), DEMSolverParameters< dim >::lagrangian_physical_properties, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta, ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::n_particle_types, and Parameters::Lagrangian::LagrangianPhysicalProperties::particle_type_number.
update_contact_information()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> void ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::update_contact_information (particle_particle_contact_info< dim > & contact_info, Tensor< 1, 3 > & tangential_relative_velocity, double & normal_relative_velocity_value, Tensor< 1, 3 > & normal_unit_vector, const ArrayView< const double > & particle_one_properties, const ArrayView< const double > & particle_two_properties, const Point< 3 > & particle_one_location, const Point< 3 > & particle_two_location, const double dt) inline protected
Update the contact pair information for all contact force calculations.
Parameters
[out] contact_info Contact information of a particle pair in neighborhood.
[out] tangential_relative_velocity Tangential relative velocity.
[out] normal_unit_vector Normal vector of the contact.
[in] particle_one_properties Properties of particle one in contact.
[in] particle_two_properties Properties of particle two in contact.
[in] particle_one_location Location of particle one in contact.
[in] particle_two_location Location of particle two in contact.
[in] dt DEM time step.
Definition at line 165 of file particle_particle_contact_force.h.
References particle_particle_contact_info< dim >::tangential_overlap.
vec_particle_type_index()
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> unsigned int ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::vec_particle_type_index (const unsigned int i, const unsigned int j) inline private
Return the index for accessing the properties vectors for a given combinations of particle types.
Parameters
i First particle type index.
j Second particle type index.
Returns
index associated with the combinations of particle types.
Definition at line 1387 of file particle_particle_contact_force.h.
References ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::n_particle_types.
Member Data Documentation
dmt_cut_off_threshold
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> const double ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::dmt_cut_off_threshold private
Definition at line 1740 of file particle_particle_contact_force.h.
effective_coefficient_of_friction
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_friction private
Definition at line 1735 of file particle_particle_contact_force.h.
effective_coefficient_of_restitution
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_restitution private
Definition at line 1734 of file particle_particle_contact_force.h.
effective_coefficient_of_rolling_friction
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_coefficient_of_rolling_friction private
Definition at line 1736 of file particle_particle_contact_force.h.
effective_hamaker_constant
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_hamaker_constant private
Definition at line 1738 of file particle_particle_contact_force.h.
effective_shear_modulus
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_shear_modulus private
Definition at line 1733 of file particle_particle_contact_force.h.
effective_surface_energy
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_surface_energy private
Definition at line 1737 of file particle_particle_contact_force.h.
effective_youngs_modulus
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::effective_youngs_modulus private
Definition at line 1732 of file particle_particle_contact_force.h.
model_parameter_beta
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> std::vector<double> ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::model_parameter_beta private
Definition at line 1739 of file particle_particle_contact_force.h.
n_particle_types
template<int dim, Parameters::Lagrangian::ParticleParticleContactForceModel contact_model, Parameters::Lagrangian::RollingResistanceMethod rolling_friction_model> unsigned int ParticleParticleContactForce< dim, contact_model, rolling_friction_model >::n_particle_types private
Definition at line 1731 of file particle_particle_contact_force.h.
The documentation for this class was generated from the following files:
/home/runner/work/lethe/lethe/include/dem/particle_particle_contact_force.h
/home/runner/work/lethe/lethe/source/dem/particle_particle_contact_force.cc